const assert=require('node:assert/strict'),fs=require('node:fs');
const html=fs.readFileSync('newsmuncher/templates/pet_profile.html','utf8');
for(const id of ['sourceTitleDraft','sourceBodyDraft','responseTitleDraft','responseBodyDraft'])assert(html.includes(`id="${id}"`));
assert.match(html,/<input id="responseTitleDraft" type="hidden"/);
assert.match(html,/<input id="sourceTitleDraft" type="hidden"/);
assert(!html.includes('<textarea id="sourceTitleDraft"'));
assert(!html.includes('<textarea id="responseTitleDraft"'));
for(const label of ['DATING','DRIVEL','WIKIPEDIA','POEM','PEOPLE'])assert(html.includes(`'${label}'`));
assert(html.includes('aria-label="{{ label }}"'));
for(const label of ['MUNGE IT','NOMINATE'])assert(html.includes('>'+label+'<'));
for(const removed of ['>EDIT<','>SAVE<','>CANCEL<','IMAGE GENERATION MODE','SHIZZALISE'])assert(!html.includes(removed));
assert(!html.includes("path='profile-editing.js'"));
const css=fs.readFileSync('newsmuncher/static/styles.css','utf8');
assert.match(css,/#sourceEditor\s*\{[^}]*padding-top:\s*calc\(clamp\(185px, 24vw, 235px\) \* \.58\)/s);
assert.match(css,/#responseEditor\s*\{\s*padding-top:\s*clamp\(10px, 1\.5vw, 16px\)/);
assert(!css.includes(':is(.profile-container, #outputContainer)::after'));
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);
console.log('Creator uses direct source/result editors and simplified actions.');
